---
- name: Check files
  include_tasks: 01_check.yaml

- name: Run a script
  script: file/test1.py -p 12312
  args:
    executable: python3



  #- name: Update version or install traefik
  #  include_tasks: 01_update.yaml
  #  when: result_checking_traefik_bin_file_for_install.matched != 1
  #
  #- name: Cleaning directories with config files
  #  include_tasks: 01_cleaning_system.yaml
  #  when: result_checking_traefik_bin_file_for_install.matched == 1
  #
  #- name: Install traefik and configs
  #  include_tasks: 01_install.yaml

- name: Remove old versions
  become: true
  shell: >-
    find /usr/bin/traefik_*
    -not -name "traefik_{{ traefik_distr_ver }}"
    -exec rm -v {} \;
  register: result
  changed_when: 'result.stdout'
  when: result_checking_traefik_bin_all_file.matched > 1
  notify:
    - restart_traefik
