---
- name: restart_traefik
  become: true
  systemd:
    name: traefik
    state: restarted
    enabled: true
    daemon_reload: true
  when: molecule_test_run is undefined or
        molecule_test_run
