---
all:
  vars:
    molecule_test_run: true
    traefik_log_level: 'DEBUG'
    traefik_api_debug: true
    traefik_metrics_port: 8081
    traefik_dashboard_port: 8083
    traefik_providers:
      docker:
        endpoint: "tcp://1.1.1.1:2376"
        exposedByDefault: false
        defaultRule: "Host(`{{'{{'}} .Name }}.example.com`)"
        useBindPortIP: false
    traefik_http_dynamic_config:
      - name: 'test_1'
        services_url: 'http://172.16.1.10:9000'
        domain: 'testdomain.example.com'
        tls_resolver:
          main: 'testdomain.example.com'
          sans: '*.testdomain.example.com'
      - name: 'test_2'
        services_url: 'http://172.16.1.10:9000'
        domain: 'dom1.example.com'
        tls: {}
      - name: 'test_3'
        services_url: 'http://172.16.1.10:9000'
        domain: 'dom2.example.com'
      - name: 'test_4'
        services_url: 'http://172.16.1.10:9000'
        raw_domain: >-
          'HostRegexp(`testdomain2.example.com`,
          `{subdomain:[a-zA-Z0-9-]+}.testdomain2.example.com`)'
        tls_resolver:
          main: 'testdomain2.example.com'
          sans: '*.testdomain2.example.com'
      - name: 'test_5'
        services_url: 'http://172.16.1.10:9000'
        raw_domain: >-
          'HostRegexp(`testdomain3.example.com`)'
        tls_simple_acme: true
    traefik_http_and_https_config:
      - name: 'test_1'
        services_url: 'http://127.0.0.1:8080/'
        domain: 'test1.local'
    traefik_tcp_dynamic_config:
      - name: 'test_1'
        port: 8090
        services_address: 'git.example.com:22'
    traefik_tls_provider_environments:
      - name: "AWS_PROFILE"
        value: "default"
      - name: "AWS_ACCESS_KEY_ID"
        value: "token_access"
      - name: "AWS_SECRET_ACCESS_KEY"
        value: "token_secret"
    traefik_le_caserver: >-
      https://acme-staging-v02.api.letsencrypt.org/directory
    traefik_le_challenge_type: "dnsChallenge"
    traefik_le_email: "main_email@example.com"
    traefik_le_dns_challenge_provider: "route53"
    traefik_forwardedheaders:
      forwardedHeaders:
        trustedIPs:
          - "127.0.0.1/32"
          - "172.16.0.0/16"
          - "172.20.100.0/24"
    traefik_tls_cert: |
      -----BEGIN CERTIFICATE-----
      MIIEJzCCAw+gAwIBAgIBBDANBgkqhkiG9w0BAQsFADCBmjELMAkGA1UEBhMCUlUx
      GDAWBgNVBAgTD1ByaW1vcnNraXkga3JheTEUMBIGA1UEBxMLVmxhZGl2b3N0b2sx
      FzAVBgNVBAoTDlZTVCBjb25zdWx0aW5nMQ0wCwYDVQQLEwRJbmMuMQwwCgYDVQQD
      EwNWU1QxJTAjBgkqhkiG9w0BCQEWFm1haWxAdnN0Y29uc3VsdGluZy5uZXQwHhcN
      MjAwOTE1MDM1NDAwWhcNMjEwOTE1MDM1NDAwWjBtMQswCQYDVQQGEwJSVTELMAkG
      A1UECBMCMjUxCzAJBgNVBAcTAlZMMQwwCgYDVQQKEwNWU1QxDDAKBgNVBAsTA1ZT
      VDEMMAoGA1UEAxMDVlNUMRowGAYJKoZIhvcNAQkBFgt2c3RAbWFpbC5ydTCCASIw
      DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALfx07fKv2Cjmu1xmv4yJTdLPurr
      X1rDNGdT551QX4ZkQHhv1oMI/kezHaNLuPQXnTJIRqGXBHhyvinBdWEuuU3rKMJv
      g5HpbUaMnu7pEHe9fxmtgYv8aFu8hCROefrdQdj/xu953G004E372SG8OuV3s+ca
      +dvA4ma6ykFQhPRA8LFpfW5s9qzgVe6AbeFn3xE/k33a7Jhw5sSgS8ahUmjayFDU
      GHiqTbCDTzHhPwNYpsbPhYl+mDPqJs/V9rKZ4tkp5KtB6Zi3rbsFe2HTfbmIBLb8
      CxpJOda+IlUXyWff5X6ffRggwaHQ9MsMTY4EOR9cEEOQqNd87mhPwnt2irkCAwEA
      AaOBozCBoDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRZXpUlSMz7Xn7R238YlRlC
      vn6+GTALBgNVHQ8EBAMCBeAwMQYDVR0RBCowKIITdHJhZWZpay5zYW5kYm94Lmxh
      bocErBABeIELdnN0QG1haWwucnUwEQYJYIZIAYb4QgEBBAQDAgZAMB4GCWCGSAGG
      +EIBDQQRFg94Y2EgY2VydGlmaWNhdGUwDQYJKoZIhvcNAQELBQADggEBAFMMXAmO
      VceME/Ig6Jo7TTpaAB4gS7lEpGg8mU7iUUCRN/hfGmvdobRP0x9HIR+/Qy7Qoa4x
      UIArJgbZcN4RbHLQBmM23fWNGicLQZxVXcJ0Vp4Qu98aeoSRK3+UbVRs65OX1Akm
      a9/yxhkZfAFcuzK7d+8NxKdTB2LjgEi+P/bdCyGATs/avlTSLO2xrAq3N0gsdPFB
      yYZV2iYMGz9KVJ7cS6/ySQ9DlVRoKMDVhvGtbFozbvD34OsEANRGLFU2SdBw2hIs
      28Uq9OXxx7sQjjX9/cG75nEpstCldXgg0Va24Y7RXNhunbC2qTLnXNHdZn+4Fd9k
      DEkKriv9yWu9fX4=
      -----END CERTIFICATE-----
    traefik_tls_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAt/HTt8q/YKOa7XGa/jIlN0s+6utfWsM0Z1PnnVBfhmRAeG/W
      gwj+R7Mdo0u49BedMkhGoZcEeHK+KcF1YS65Tesowm+DkeltRoye7ukQd71/Ga2B
      i/xoW7yEJE55+t1B2P/G73ncbTTgTfvZIbw65Xez5xr528DiZrrKQVCE9EDwsWl9
      bmz2rOBV7oBt4WffET+TfdrsmHDmxKBLxqFSaNrIUNQYeKpNsINPMeE/A1imxs+F
      iX6YM+omz9X2spni2Snkq0HpmLetuwV7YdN9uYgEtvwLGkk51r4iVRfJZ9/lfp99
      GCDBodD0ywxNjgQ5H1wQQ5Co13zuaE/Ce3aKuQIDAQABAoIBAGFxrHTq5SMuyH4M
      9sy+h9SY+gW9FtCgJHywiDxgPZqWNUkYBg14kCwviP3euWYltFLU0wX7WJTuRCse
      ny4ScHwEnZ0TMiH0BL2g9PkfYmfsbQ6PSdd8qVQfs+j/4cKxv5ZTOXHXnpwDrOfj
      CQ3EB3dUSGufcMmnjshZH5gmLaiubxTYTV4X83XHICEEs7YNAgoxZLWU0iSssseo
      VD4pEnxik0gZIzNh2HRpJuCCuk7T9PSxZwUqI8yUM8TcdPFaX1CVxcKTTuPOkLU1
      FzvBm94ecpjoGHhI026dHymVXGTX1nHKeOQay4m+ANutKDeOTBVzqMh8uTDxffcY
      +nZNLpkCgYEA8aGKKOcZZBXZcH0f1oNpEUhrNMArUunAjBmCEmKYSEALih7UIlML
      px4ZTZYSSa6vtI/FvXAJFzeUF6FRhotuXl/xud7PbPSpKzNhO/vkYI9om4iuTe4V
      6Bt+vCZKC/obvBZzKPYq5FuJ5p1H8t5UPU3s0INu6BmivY6Mi8YnEO8CgYEAwuIZ
      3GxFH5tFFjJbBrCPiLp0fZmeBgF1tTM2rRSYnZQPO/40M7LglmRj74QcvqpXIRPR
      nGYT8Vc9NRbj7c1dCMeyb24wUbuCUT7or+KSosNgEqmlUEZtMKwCb2FHtz+ESAKw
      iLPusyMjTaOgyMj5tWLrZA65bqU0UfgL90FpztcCgYEA3eygGDEpAOOQceB5/Wt0
      dIsu66QUJnLKheJntLsZYkJwVss5ysy7RyI92ySaZ1Ipzoy98N+Ved1yBsIDPq+R
      DtzQBwa9PDT5qtPl2lHfz0/no/JFJQ4m0KdwHx6Lo7RzBK0Z1+VAP7xTS5vpGQda
      F3QarOgKVOI2tiLWswmrl8ECgYBOoP8iKiTxjaogPIzxdAdVeTVK/9H8RlaBl3o1
      9xtkaLqE0Bmryj5HL5YKq1kVrJCe7eoimiTtuO8fHm80ISmqQzhBMUoZj/gSY7lq
      TZYwSXfXz869Rs0DWENbQPq4es4aZ8tmPILQkBrMVnqmyD/H6XNj2XUDqXAkqlnZ
      lvDj3QKBgQDrbenRM+aZ/gGnmSFX/bEWEMfP9henvza9KZiq3TjzN2YSY+xL1NAx
      DxDbIV+PFMVAX9OynGJuDtc7dwWtVH5YqlCxmb5gRfLiYH1qIj6ek/l1ASVPztLI
      pEsGJQKqucl+D1lho20uWAoCeeXOSTLwpi7TdIwJEtciMMvQtk1LvQ==
      -----END RSA PRIVATE KEY-----
