---
dependency:
  name: galaxy
  enabled: false
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: .
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8 molecule/
  ansible-lint
platforms:
  - name: Ubuntu-20.04
    image: registry.gitlab.com/vstconsulting/images:python
  - name: Centos-7
    image: registry.gitlab.com/vstconsulting/images:centos7
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
  ansible_args:
    - --inventory=inventory.yaml
verifier:
  name: testinfra
  options:
    vv: true
